import { Cron } from "croner";

/**
 * Validates if a string is a valid cron expression.
 */
export function isValidCron(pattern: string): boolean {
  if (!pattern) return false;
  try {
    new Cron(pattern);
    return true;
  } catch {
    return false;
  }
}

/**
 * Formats time numbers to double digits.
 */
function padZero(n: number): string {
  return String(n).padStart(2, "0");
}

/**
 * Translates day numbers or codes into readable names.
 */
const DAY_MAP: Record<string, string> = {
  "0": "Sunday",
  "7": "Sunday",
  sun: "Sunday",
  "1": "Monday",
  mon: "Monday",
  "2": "Tuesday",
  tue: "Tuesday",
  "3": "Wednesday",
  wed: "Wednesday",
  "4": "Thursday",
  thu: "Thursday",
  "5": "Friday",
  fri: "Friday",
  "6": "Saturday",
  sat: "Saturday",
};

/**
 * Translates a cron expression into a friendly human-readable format.
 * Focuses on patterns generated by the ScheduleBuilder UI.
 */
export function describeCron(cron: string): string {
  if (!isValidCron(cron)) {
    return "Invalid schedule";
  }

  const parts = cron.trim().split(/\s+/);
  if (parts.length < 5 || parts.length > 6) {
    return `Cron: ${cron}`;
  }

  const [min, hour, dom, month, dow] = parts;

  // 1. Every N minutes: "*/N * * * *" or "*/1 * * * *"
  if (
    min.startsWith("*/") &&
    hour === "*" &&
    dom === "*" &&
    month === "*" &&
    dow === "*"
  ) {
    const n = min.substring(2);
    return n === "1" ? "Every minute" : `Every ${n} minutes`;
  }

  // 2. Every N hours: "0 */N * * *" or "M */N * * *"
  if (
    !min.includes(",") &&
    !min.includes("/") &&
    hour.startsWith("*/") &&
    dom === "*" &&
    month === "*" &&
    dow === "*"
  ) {
    const n = hour.substring(2);
    const minuteStr = min === "0" ? "" : ` at minute ${min}`;
    return n === "1"
      ? `Every hour${minuteStr}`
      : `Every ${n} hours${minuteStr}`;
  }

  // 3. Every N days at HH:MM: "MM HH */N * *"
  if (
    !min.includes(",") &&
    !min.includes("/") &&
    !min.includes("*") &&
    !hour.includes(",") &&
    !hour.includes("/") &&
    !hour.includes("*") &&
    dom.startsWith("*/") &&
    month === "*" &&
    dow === "*"
  ) {
    const n = dom.substring(2);
    const timeStr = `${padZero(parseInt(hour, 10))}:${padZero(parseInt(min, 10))}`;
    return n === "1"
      ? `Every day at ${timeStr}`
      : `Every ${n} days at ${timeStr}`;
  }

  // 4. Daily at HH:MM: "MM HH * * *"
  if (
    !min.includes(",") &&
    !min.includes("/") &&
    !min.includes("*") &&
    !hour.includes(",") &&
    !hour.includes("/") &&
    !hour.includes("*") &&
    dom === "*" &&
    month === "*" &&
    dow === "*"
  ) {
    const timeStr = `${padZero(parseInt(hour, 10))}:${padZero(parseInt(min, 10))}`;
    return `Every day at ${timeStr}`;
  }

  // 5. Weekly on selected days: "MM HH * * DOW"
  if (
    !min.includes(",") &&
    !min.includes("/") &&
    !min.includes("*") &&
    !hour.includes(",") &&
    !hour.includes("/") &&
    !hour.includes("*") &&
    dom === "*" &&
    month === "*" &&
    dow !== "*"
  ) {
    const timeStr = `${padZero(parseInt(hour, 10))}:${padZero(parseInt(min, 10))}`;
    const days = dow.split(",").map((d) => {
      const lower = d.toLowerCase();
      return DAY_MAP[lower] || d;
    });

    let daysStr = "";
    if (days.length === 1) {
      daysStr = days[0];
    } else if (days.length === 2) {
      daysStr = `${days[0]} and ${days[1]}`;
    } else if (days.length === 7) {
      return `Every day at ${timeStr}`;
    } else {
      daysStr = `${days.slice(0, -1).join(", ")}, and ${days[days.length - 1]}`;
    }

    return `Weekly on ${daysStr} at ${timeStr}`;
  }

  // 6. Monthly on a specific day of the month: "MM HH DOM * *"
  if (
    !min.includes(",") &&
    !min.includes("/") &&
    !min.includes("*") &&
    !hour.includes(",") &&
    !hour.includes("/") &&
    !hour.includes("*") &&
    dom !== "*" &&
    month === "*" &&
    dow === "*"
  ) {
    const timeStr = `${padZero(parseInt(hour, 10))}:${padZero(parseInt(min, 10))}`;
    let dayStr = "";
    if (dom === "L") {
      dayStr = "the last day";
    } else if (dom === "15") {
      dayStr = "the 15th (middle)";
    } else {
      const dNum = parseInt(dom, 10);
      dayStr = Number.isNaN(dNum)
        ? `day ${dom}`
        : `the ${getOrdinalSuffix(dNum)} day`;
    }

    let warning = "";
    if (dom !== "L" && dom !== "15") {
      const dNum = parseInt(dom, 10);
      if (!Number.isNaN(dNum) && dNum > 28) {
        warning = ` (Warning: day is > 28; this will skip in shorter months like February)`;
      }
    }
    return `Monthly on ${dayStr} of the month at ${timeStr}${warning}`;
  }

  // Fallback for general valid crons
  return `Cron: ${cron}`;
}

/**
 * Helper to get the ordinal suffix for day numbers.
 */
function getOrdinalSuffix(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}

/**
 * Returns a human-readable description of a interval (in seconds).
 */
export function describeInterval(seconds: number): string {
  if (seconds <= 0) return "Never";

  if (seconds < 60) {
    return seconds === 1 ? "Every second" : `Every ${seconds} seconds`;
  }

  const minutes = seconds / 60;
  if (Number.isInteger(minutes)) {
    if (minutes < 60) {
      return minutes === 1 ? "Every minute" : `Every ${minutes} minutes`;
    }

    const hours = minutes / 60;
    if (Number.isInteger(hours)) {
      if (hours < 24) {
        return hours === 1 ? "Every hour" : `Every ${hours} hours`;
      }

      const days = hours / 24;
      if (Number.isInteger(days)) {
        return days === 1 ? "Every day" : `Every ${days} days`;
      }
    }
  }

  // Fallback composite formatting
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;

  const parts: string[] = [];
  if (h > 0) parts.push(h === 1 ? "1 hour" : `${h} hours`);
  if (m > 0) parts.push(m === 1 ? "1 minute" : `${m} minutes`);
  if (s > 0) parts.push(s === 1 ? "1 second" : `${s} seconds`);

  return `Every ${parts.join(", ")}`;
}

/**
 * Combined scheduler description helper.
 */
export function describeSchedule(
  intervalSeconds?: number | null,
  cronExpression?: string | null,
): string {
  if (cronExpression) {
    return describeCron(cronExpression);
  }
  if (intervalSeconds) {
    return describeInterval(intervalSeconds);
  }
  return "Manual only";
}

/**
 * Converts a schedule interval in seconds to a 6-element or 5-element cron pattern.
 * This is used so interval-based schedules can use Croner for next-run calculation.
 */
export function intervalToCron(seconds: number): string {
  if (seconds < 60) {
    return `*/${seconds} * * * * *`;
  }
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) {
    return `0 */${minutes} * * * *`;
  }
  const hours = Math.floor(minutes / 60);
  if (hours < 24) {
    return `0 0 */${hours} * * *`;
  }
  const days = Math.floor(hours / 24);
  return `0 0 0 */${days} * *`;
}
